<?php

/**
 * Implements hook_menu().
 * @return array
 */
function pss_extras_menu() {
    $items = array();
    $items['admin/pss-settings'] = array(
      'title' => t('Site Settings'),
      'type' => MENU_NORMAL_ITEM,
      'weight' => 8,
      'description' => t('PSS Site Settings'),
      'file' => 'inc/pss_settings_page.inc.php',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('pss_extras_settings_page'),
      'access callback' => 'pss_extras_user_has_role',
      'access arguments' => array(array('site administrator')),
    );
    return $items;
}

function pss_extras_user_has_role($roles = array()) {
    global $user;
    $roles[] = 'administrator';
    foreach ($roles as $role) {
        if (in_array($role, $user->roles)) {
            return TRUE;
        }
    }
    return FALSE;
}

/**
 * Implements hook_block_info().
 */
function pss_extras_block_info() {
    $blocks['news-type'] = array(
      'info' => t('News type'),
    );
    $blocks['top-newsletter-subscribe-block'] = array(
      'info' => t('Top newsletter subscribe block'),
    );
    $blocks['slim-newsletter-subscribe-block'] = array(
      'info' => t('Slim newsletter subscribe block'),
    );
    $blocks['taxonomy-tags'] = array(
      'info' => t('Taxonomy tags list')
    );
    return $blocks;
}

/**
 * Implements hook_block_view()
 *
 * @param string $delta
 * @return array
 * @throws Exception
 */
function pss_extras_block_view($delta = '') {
    $block = array();
    switch ($delta) {
        case 'news-type' :
            $block['subject'] = '';
            $block['content'] = __pss_extras_generate_news_type_block();
            break;
        case 'top-newsletter-subscribe-block' :
            $block = array(
              'subject' => '',
              'content' => '
                    <div id="mail_chimp_signup">
                        <div class="pss-title-wrapper">
                          <p class="pss-title">'.t('Newsletter').'</p>
                        </div>
                        <div class="pss-message-wrapper">
                            <p class="pss-message">'.t('Leave yours e-mail address and we will provide you fresh news in field od security').'</p>
                        </div>
                        <div id="mc_embed_signup">
                        <form action="//pss-magazine.us16.list-manage.com/subscribe/post?u=afac2614cb11484bde653fcd8&amp;id=af00818c48" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" novalidate>
                            <div id="mc_embed_signup_scroll">
                            <label for="mce-EMAIL">'.t('Email').'</label>
                            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
                            <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_afac2614cb11484bde653fcd8_af00818c48" tabindex="-1" value=""></div>
                            <input type="submit" value="'.t('Subscribe').'" name="subscribe" id="mc-embedded-subscribe" class="button form-submit">
                            </div>
                        </form>
                        </div>
                    </div>
                    <div id="yumpy_read_last">
                        '.__pss_extras_generate_yumpu_front_block().'
                    </div>
              '
            );
            break;
        case 'slim-newsletter-subscribe-block' :
            $block = array(
              'subject' => '',
              'content' => '
                    <div id="mail_chimp_signup">
                        <div id="mc_embed_signup">
                        <form action="//pss-magazine.us16.list-manage.com/subscribe/post?u=afac2614cb11484bde653fcd8&amp;id=af00818c48" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" novalidate>
                            <div id="mc_embed_signup_scroll">
                            <label for="mce-EMAIL">'.t('Email').'</label>
                            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
                            <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_afac2614cb11484bde653fcd8_af00818c48" tabindex="-1" value=""></div>
                            <input type="submit" value="'.t('Subscribe').'" name="subscribe" id="mc-embedded-subscribe" class="button form-submit">
                            </div>
                        </form>
                        </div>
                    </div>
                    '
            );
            break;
        case 'taxonomy-tags':
            $block['subject'] = '';
            $block['content'] = __pss_extras_generate_taxonomy_tags_block();
            break;
    }
    return $block;
}

/**
 * Implements hook_theme().
 */
function pss_extras_theme($existing, $type, $theme, $path) {
    return array(
      'news_type_block' => array(
        'template' => 'news-type-block',
        'path' => drupal_get_path('module', 'pss_extras') . '/theme',
      ),
      'news_type_block_row' => array(
        'template' => 'news-type-block-row',
        'path' => drupal_get_path('module', 'pss_extras') . '/theme',
      ),
      'news_type_block_single' => array(
        'template' => 'news-type-block-single',
        'path' => drupal_get_path('module', 'pss_extras') . '/theme',
      ),
    );
}

function pss_extras_preprocess_html(&$variables) {
    if (path_is_admin(current_path())) {
        drupal_add_css(drupal_get_path('module', 'pss_extras') . '/css/pss-admin.css');
    }
}

/**
 * Implements hook_preprocess_node().
 */
function pss_extras_preprocess_node(&$vars) {
    $lang_lat = 'lat';
    $lang_none = LANGUAGE_NONE;
    $vars['current_magazine_number'] = __pss_extras_get_current_magazine_number();
    if ($vars['type'] == 'article' && $vars['view_mode'] == 'full') {
        $magazine_number_id = isset($vars['field_magazine_number_reference'][$lang_lat]) ? $vars['field_magazine_number_reference'][$lang_lat][0]['target_id'] : $vars['field_magazine_number_reference'][$lang_none][0]['target_id'];
        $magazine_number = node_load($magazine_number_id);
        $magazine_number_value = isset($magazine_number->field_magazine_number[$lang_lat]) ? $magazine_number->field_magazine_number[$lang_lat][0]['value'] : $magazine_number->field_magazine_number[$lang_none][0]['value'];
        $vars['magazine_number'] = $magazine_number_value;
        $period = isset($magazine_number->field_magazine_for_period[$lang_lat]) ? $magazine_number->field_magazine_for_period[$lang_lat] : $magazine_number->field_magazine_for_period[$lang_none];
        $year = date('Y', strtotime($period[0]['value']));
        $month_1 = date('F', strtotime($period[0]['value']));
        $month_2 = date('F', strtotime($period[0]['value2']));
        $vars['for_period_year'] = $year;
        $vars['for_period_months'] = t($month_1) . '/' . t($month_2);
        $uid = isset($vars['uid']) ? $vars['uid'] : 0;
        $created_by = user_load($uid);
        $account_view = user_view($created_by, 'teaser');
        $vars['created_by_picture'] = drupal_render($account_view);
        $current_magazine_number = __pss_extras_get_current_magazine_number();
        $from_current_value = (int) $magazine_number_value == (int) $current_magazine_number;
        $user_has_admin_role = pss_extras_user_has_role(array('site administrator'));
        if (!$user_has_admin_role && $from_current_value &&
          isset($vars['body'], $vars['body'][0], $vars['content']['body'][0]['#markup'])
        ) {
            $body_value = $vars['body'][0]['value'];
            $summary_value = $vars['body'][0]['summary'];
            if (!empty($summary_value)) {
                $vars['body'][0]['value'] = $summary_value;
                $vars['content']['body'][0]['#markup'] = $summary_value;
            }
            else {
                $alter = array(
                  'max_length' => variable_get('pss_current_magazine_number_body_char_count', 400),
                  'word_boundary' => 'yes',
                  'ellipsis' => 'yes',
                  'html' => 'yes'
                );
                $trimmed = views_trim_text($alter, $body_value);
                $vars['body'][0]['value'] = $trimmed;
                $vars['body'][0]['safe_value'] = $trimmed;
                $vars['content']['body'][0]['#markup'] = $trimmed;
            }
        }
    }
    if($vars['type'] == 'article' && $vars['view_mode'] == 'teaser') {
        $magazine_number_id = isset($vars['field_magazine_number_reference'], $vars['field_magazine_number_reference'][0]) ? $vars['field_magazine_number_reference'][0]['target_id'] : null;
        $magazine_number = $magazine_number_id ? node_load($magazine_number_id) : null;
        $from_current_value = true;
        if ($magazine_number) {
            $magazine_number_value = isset($magazine_number->field_magazine_number[$lang_lat]) ? $magazine_number->field_magazine_number[$lang_lat][0]['value'] : $magazine_number->field_magazine_number[$lang_none][0]['value'];
            $vars['magazine_number'] = $magazine_number_value;
            $current_magazine_number = __pss_extras_get_current_magazine_number();
            $from_current_value = (int) $magazine_number_value == (int) $current_magazine_number;
        }
        $user_has_admin_role = pss_extras_user_has_role(array('site administrator'));
        if (!$user_has_admin_role && $from_current_value && isset($vars['body'], $vars['body'][0])) {
            $body_value = $vars['body'][0]['value'];
            $summary_value = $vars['body'][0]['summary'];
            if (!empty($summary_value)) {
                $vars['body'][0]['value'] = $summary_value;
                $vars['content']['body'][0]['#markup'] = $summary_value;
            }
            else {
                $alter = array(
                  'max_length' => variable_get('pss_current_magazine_number_body_char_count', 400),
                  'word_boundary' => 'yes',
                  'ellipsis' => 'yes',
                  'html' => 'yes'
                );
                $trimmed = views_trim_text($alter, $body_value);
                $vars['body'][0]['value'] = $trimmed;
                $vars['body'][0]['safe_value'] = $trimmed;
                $vars['content']['body'][0]['#markup'] = $trimmed;
            }
        }
    }
    if ($vars['type'] == 'page' && $vars['nid'] == '152') {
        drupal_add_library("system", "ui.accordion");
        drupal_add_js('
			jQuery(document).ready(
				function() {
					jQuery("#accordion").accordion();
			});', 'inline');
    }
}

function pss_extras_preprocess_user_picture(&$variables) {
    $variables['user_picture'] = '';
    if (variable_get('user_pictures', 0)) {
        $account = $variables['account'];
        if (!empty($account->picture)) {
            if (is_numeric($account->picture)) {
                $account->picture = file_load($account->picture);
            }
            if (!empty($account->picture->uri)) {
                $filepath = $account->picture->uri;
            }
        }
        elseif (variable_get('user_picture_default', '')) {
            $filepath = variable_get('user_picture_default', '');
        }
        if (isset($filepath)) {
            $alt = t("@user's picture", array('@user' => format_username($account)));
            if (module_exists('image') && file_valid_uri($filepath) && $style = variable_get('user_picture_style', '')) {
                $variables['user_picture'] = theme('image_style', array(
                  'style_name' => $style,
                  'path' => $filepath,
                  'alt' => $alt,
                  'title' => $alt
                ));
            }
            else {
                $variables['user_picture'] = theme('image', array(
                  'path' => $filepath,
                  'alt' => $alt,
                  'title' => $alt
                ));
            }
            if (!empty($account->uid) && user_access('access user profiles')) {
                $attributes = array(
                  'attributes' => array('title' => t('View user profile.')),
                  'html' => TRUE
                );
                $variables['user_picture'] = '<div class="image-wrapper">' . $variables['user_picture'] . '</div>';
            }
        }
    }
}

/**
 * Implements hook_preprocess_page().
 */
function pss_extras_preprocess_page(&$vars) {
    $vars['current_magazine_number'] = __pss_extras_get_current_magazine_number();
    $vars['print_yumpu'] = 0;
    if (isset($vars['node']) && $vars['node']->type == 'magazine_number')  {
        $magazine_number = isset($vars['node']->field_magazine_number[LANGUAGE_NONE][0]['value']) ? $vars['node']->field_magazine_number[LANGUAGE_NONE][0]['value'] : null;
        $embed_link = isset($vars['node']->field_magazine_embed[LANGUAGE_NONE][0]['url']) ? $vars['node']->field_magazine_embed[LANGUAGE_NONE][0]['url'] : null;
        if (isset($magazine_number, $embed_link) && $magazine_number != $vars['current_magazine_number']) {
            $vars['print_yumpu'] = 1;
            $vars['yumpu_link'] = $embed_link;
            $vars['yumpu_text'] = t('read <br> number') . ' ' . $magazine_number;
        }
    }
}

function pss_extras_preprocess_block(&$vars, $hook) {
    if ($vars['block']->region == 'menu') {
        if ($vars['block']->module == 'search') {
            $vars['content'] = '<div class="toggle-holder"></div>' . $vars['content'];
            drupal_add_js(drupal_get_path('module', 'pss_extras') . '/scripts/pss_search.js');
        }
        if ($vars['block']->module == 'superfish') {
            drupal_add_js(drupal_get_path('module', 'pss_extras') . '/scripts/waypoints.js');
            drupal_add_js(drupal_get_path('module', 'pss_extras') . '/scripts/waypoints-sticky.js');
            drupal_add_js("
            jQuery(document).ready(function () {
                jQuery('#header .section-1').waypoint('sticky');
            });
            ", 'inline');
        }
    }
    if ($vars['block']->module == 'views') {
        drupal_add_js(drupal_get_path('module', 'pss_extras') . '/scripts/jquery.dotdotdot.min.js');
        drupal_add_js(drupal_get_path('module', 'pss_extras') . '/scripts/pss.dotdotdot.js');
    }
    if ($vars['block']->module == 'search') {
        $contextual_links_key = array_search('contextual-links-region', $vars['classes_array']);
        if ($contextual_links_key) {
            unset($vars['classes_array'][$contextual_links_key]);
        }
    }
}

function pss_extras_views_query_alter(&$view, &$query) {
    $nid = arg(1);
    $node = NULL;
    if ($nid) {
        $node = node_load($nid);
    }
    if ($node && $node->type == 'magazine_number' && $view->name === 'news_view' && $view->current_display == 'block_view_filter_archive') {
        $number = $node->field_magazine_number[LANGUAGE_NONE][0]['value'];
        $query->where[1]['conditions'][2]['value'] = $number;
    }
}

function pss_extras_views_pre_render(&$view) {
//    if ($view->name == 'news_view') {
//        foreach ($view->result as $key => $result) {
//            if (property_exists($result, 'node_title')) {
//                $result->node_title = mb_ucfirst(mb_strtolower($result->node_title));
//            }
//        }
//    }
}

function pss_extras_form_alter(&$form, $form_state, $form_id) {
    global $user;
    if ($form_id == 'views_exposed_form' && $form['#id'] == 'views-exposed-form-magazine-number-archive-page') {
        $currentYear = (int) $form['field_magazine_for_period_value']['value']['#default_value'];
        $minMagazineYear = __pss_extras_get_min_magazine_year();
        $minRange = $currentYear - $minMagazineYear;
        $form['field_magazine_for_period_value']['value']['#date_year_range'] = "-{$minRange}:+0";
    }
    if ($form_id == 'comment_node_article_form' && $user->uid) {
        $form['author']['_author']['#markup'] = '<span class="author-name">' . $form['author']['name']['#value'] . '</span>';
    }
}

function pss_extras_form_magazine_number_node_form_alter(&$form, $form_state, $form_id) {
    if ($form['#action'] == '/node/add/magazine-number') {
        $lastNums = __pss_extras_get_last_n_numbers(1);
        $old_num = reset($lastNums);
        $new_num = $old_num + 1;
        if (isset($form['title'])) {
            $form['title']['#default_value'] = 'Broj ' . $new_num;
        }
        if (isset($form['field_magazine_number'][LANGUAGE_NONE][0]['value'])) {
            $form['field_magazine_number'][LANGUAGE_NONE][0]['value']['#default_value'] = $new_num;
        }
        $last_magazine_number_node = __pss_extras_get_magazine_node_by_numbers($old_num);
        if (isset($form['field_magazine_for_period'][LANGUAGE_NONE][0]['#default_value']['value'])) {
            $old_date_str = $last_magazine_number_node->field_magazine_for_period[LANGUAGE_NONE][0]['value'];
            $new_date = date('Y-m-d H:i:s', strtotime("+2 months", strtotime($old_date_str)));
            $form['field_magazine_for_period'][LANGUAGE_NONE][0]['#default_value']['value'] = $new_date;
        }
        if (isset($form['field_magazine_for_period'][LANGUAGE_NONE][0]['#default_value']['value2'])) {
            $old_date_str1 = $last_magazine_number_node->field_magazine_for_period[LANGUAGE_NONE][0]['value2'];
            $new_date1 = date('Y-m-d H:i:s', strtotime("+2 months", strtotime($old_date_str1)));
            $form['field_magazine_for_period'][LANGUAGE_NONE][0]['#default_value']['value2'] = $new_date1;
        }
    }
}
function __pss_extras_generate_yumpu_front_block(){
    $html = '';
    if (!drupal_is_front_page()) return $html;
    $current_number = __pss_extras_get_current_magazine_number();
    $last_number = (int)$current_number - 1;
    $query = db_select('node', 'n');
    $query->join('field_data_field_magazine_number', 'mn', 'n.nid= mn.entity_id');
    $query->fields('n', array('nid'))
      ->condition('n.status', 1)
      ->condition('mn.field_magazine_number_value', $last_number);
    $nid = $query->orderBy('n.created', 'desc')
      ->range(0, 1)
      ->execute()
      ->fetchField();
    if (isset($nid) && $node = node_load($nid))  {
        $magazine_number = isset($node->field_magazine_number[LANGUAGE_NONE][0]['value']) ? $node->field_magazine_number[LANGUAGE_NONE][0]['value'] : null;
        $embed_link = isset($node->field_magazine_embed[LANGUAGE_NONE][0]['url']) ? $node->field_magazine_embed[LANGUAGE_NONE][0]['url'] : null;
        if (isset($magazine_number, $embed_link)) {
            $html .= '
                <div id="yumpu-link-wrapper">
                    <a class="yumpu-link" href="' . $embed_link . '" target="_blank">
                        <div class="yumpu-text">'.t('Read number') . ' ' . $magazine_number.'</div>
                        <div class="yumpu-image"><img src="/sites/default/files/pictures/read-number.png"></div>
                    </a>
                </div>
            ';
        }
    }
    return $html;
}

function __pss_extras_generate_taxonomy_tags_block() {
    $items = __pss_get_taxonomy_terms();
    usort($items, function ($a, $b) {
        if ($a['count'] == $b['count']) {
            $result = 0;
        }
        else {
            $result = ($a['count'] > $b['count']) ? -1 : 1;
        }
        return $result;
    }
    );
    $html = '<div class="title">/// ' . t('Tag search') . ' ///</div>';
    $html .= '<div class="view-content">';
    $counter = 1;
    foreach ($items as $item) {
        if ($counter++ == 10) {
            break;
        }
        $html .= $item['link'];
    }
    $html .= '</div>';
    return $html;
}

function __pss_extras_generate_news_type_block() {
    $content = '';
    $taxonomyVocabularyName = 'news_type';
    $taxonomyVocabulary = taxonomy_vocabulary_machine_name_load($taxonomyVocabularyName);
    $taxonomyTerms = taxonomy_get_tree($taxonomyVocabulary->vid);
    $rows = [];
    $tid2nid = __get_taxonomy_tid_2_nid();
    $lastNNums = __pss_extras_get_last_n_numbers(3);
    foreach ($taxonomyTerms as $taxonomyTerm) {
        $taxonomy = taxonomy_term_load($taxonomyTerm->tid);
        $vars = array(
          'tagLink' => url('node/' . $tid2nid[$taxonomyTerm->tid]),
          'tagImageLink' => file_create_url($taxonomy->field_news_type_image[LANGUAGE_NONE][0]['uri']),
          'tagTitle' => $taxonomy->name,
          'tagNewss' => __pss_extras_get_tag_news($taxonomyTerm->tid, $lastNNums)
        );
        $rows[] = array(
          'content' => theme('news_type_block_single', $vars),
        );
    }
    $rows[] = array(
      'content' => theme('news_type_block_single', array()),
      'classes' => array('empty-row')
    );
    $rows_string = theme('news_type_block_row', array('blocks' => $rows));
    $content .= theme('news_type_block', array(
      'content' => $rows_string,
      'title' => t('News types')
    ));
    return $content;
}

function __pss_extras_get_tag_news($tid, $lastNNums) {
    $tag_news = [];
    foreach ($lastNNums as $magazineNum) {
        $query = db_select('node', 'n');
        $query->join('taxonomy_index', 't', 'n.nid = t.nid');
        $query->join('field_data_field_magazine_number_reference', 'mnr', 'n.nid = mnr.entity_id');
        $query->leftJoin('field_data_field_magazine_number', 'mn', 'mnr.field_magazine_number_reference_target_id = mn.entity_id');
        $query->fields('n', array('nid'))
          ->condition('n.status', 1)
          ->condition('n.type', 'article')
          ->condition('mn.field_magazine_number_value', $magazineNum)
          ->condition('t.tid', $tid);
        $nid = $query->orderBy('n.created', 'desc')
          ->range(0, 1)
          ->execute()
          ->fetchField();
        if ((bool) $nid) {
            $node = node_load($nid);
            if ($node) {
                $tag_news[] = array(
                  'tagNewsNum' => $magazineNum,
                  'tagNewsTitle' => $node->title,
                  'tagNewsPath' => url('node/' . $node->nid),
                );
            }
        }
    }
    return $tag_news;
}

function __get_taxonomy_tid_2_nid() {
    return array(
      18 => 90, // Security novosti
      19 => 94, // Mendžment
      20 => 95, // Intervju
      23 => 98, // Požarna zaštita
      22 => 99, // Security praksa
      21 => 100, // Tema broja
      24 => 101, // Tehnika
      25 => 102, // Aktuelno
      26 => 103, // Da li se zna
      28 => 158, // Uvodnik
      29 => 159, // U fokusu
    );
}

function __pss_extras_get_last_n_numbers($num) {
    $nums = db_query(
      'SELECT DISTINCT field_magazine_number_value FROM field_data_field_magazine_number
        ORDER BY field_magazine_number_value DESC LIMIT ' . $num)->fetchCol();
    return $nums;
}

function __pss_extras_get_magazine_node_by_numbers($num) {
    $node = NULL;
    $nid = db_query(
      'SELECT entity_id FROM field_data_field_magazine_number
        WHERE bundle = :bundle AND field_magazine_number_value = :num ORDER BY field_magazine_number_value DESC LIMIT 1',
      [':bundle' => 'magazine_number', ":num" => $num]
    )->fetchField();
    if ($nid) {
        $node = node_load((int) $nid);
    }
    return $node;
}


function __pss_extras_get_current_magazine_number() {
    if ($cache = cache_get('pss_extras_current_magazine_number')) {
        $current_magazine_number = $cache->data;
    }
    else {
        $current_magazine_number = db_query('SELECT MAX(field_magazine_number_value) FROM field_data_field_magazine_number')->fetchField();
        cache_set('pss_extras_current_magazine_number', $current_magazine_number);
    }
    return $current_magazine_number;
}

function __pss_extras_get_min_magazine_year() {
    if ($cache = cache_get('pss_extras_min_magazine_number')) {
        $min_magazine_year = $cache->data;
    }
    else {
        $min_magazine_year = db_query('SELECT MIN(YEAR(field_magazine_for_period_value)) FROM field_data_field_magazine_for_period')->fetchField();
        cache_set('pss_extras_min_magazine_number', (int) $min_magazine_year);
    }
    return $min_magazine_year;
}

function __pss_get_taxonomy_terms() {
    if ($cache = cache_get('pss_extras_taxonomy_terms_tags')) {
        $tag_items = unserialize($cache->data);
    }
    else {
        $vid = 1; //taxonomy type tags
        $tag_items = [];
        $terms = taxonomy_get_tree($vid);
        foreach ($terms as $term) {
            $count = db_query("SELECT COUNT(nid) FROM {taxonomy_index} WHERE tid = :tid", array(':tid' => $term->tid))->fetchField();
            $tag_items[$term->tid] = array(
              'link' => l($term->name, "taxonomy/term/$term->tid"),
              'count' => $count
            );
        }
        cache_set('pss_extras_taxonomy_terms_tags', serialize($tag_items));
    }
    return $tag_items;
}

if (!function_exists('mb_ucfirst')) {
    function mb_ucfirst($str, $encoding = "UTF-8", $lower_str_end = false) {
        $first_letter = mb_strtoupper(mb_substr($str, 0, 1, $encoding), $encoding);
        $str_end = "";
        if ($lower_str_end) {
            $str_end = mb_strtolower(mb_substr($str, 1, mb_strlen($str, $encoding), $encoding), $encoding);
        }
        else {
            $str_end = mb_substr($str, 1, mb_strlen($str, $encoding), $encoding);
        }
        $str = $first_letter . $str_end;
        return $str;
    }
}